### ISSUE TITLE
ZaakInformatieObject with invalid zaak or informatieobject url gives 500 error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#76] opened 2019-09-05 07:37 UTC
**Describe the bug**
If I try to create a `ZaakInformatieObject` with a `zaak` or `informatieobject` url that does not point to the correct resource, I would expect an HTTP 400, but I get a 500 instead:

```html
ObjectDoesNotExist at /zaken/api/v1/zaakinformatieobjecten
URL did not resolve

Request Method: POST
Request URL: http://localhost:8000/zaken/api/v1/zaakinformatieobjecten
Django Version: 2.2.4
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.7.4
Python Path: ['.', '', '/usr/local/lib/python37.zip', '/usr/local/lib/python3.7', '/usr/local/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/site-packages']
Server time: do, 5 Sep 2019 07:36:10 +0000
```

**Comment by annashamray** [comment] 2019-09-25 12:13
@stevenbal Can you send your input data please? Unfortunately I can't reproduce the bug

I tried:
1. zaak = 'some-string'. The result: status=400
1. zaak = 'http://example.com/zaak' . The result: status=400
1. zaak = '/zaken/api/v1/zaken/{random uuid}'. The result: status=400

**Comment by stevenbal** [comment] 2019-09-26 08:14
@annashamray It seems that something has changed, causing the API to return valid JSON with a code 400 instead of 500, so that issue is resolved. There is however still the issue of different errors (which is described in https://github.com/open-zaak/open-zaak/issues/77).

**Comment by annashamray** [comment] 2019-09-26 08:35
Yeah, I saw that issue with error codes. 
So I close this issue

**Closed by annashamray** 2019-09-26 08:35 UTC
Labels: bug
