### ISSUE TITLE
Can still not publish a new zaaktype-version due to an unknown error

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1247] opened 2022-08-17 14:13 UTC
**General information**
Open Zaak version: 1.7.2

**Describe the bug**
When you try to publish a new zaaktype version, you get the error message that "you need to correct the errors below" but no errors are shown.

![image](https://user-images.githubusercontent.com/96970/185156366-ea17a107-6e0e-4819-b990-18a867a23a54.png)

**Comment by alextreme** [comment] 2022-08-30 10:38
Investigated for SWF.

Issue is that the calendar isn't shown, as described by the client. Was simply a matter of updating django-admin-index to 2.0.1 or newer.

![image](https://user-images.githubusercontent.com/226839/187415621-4c3d4682-ee04-4d37-92e3-d13d80561fa8.png)

**Comment by sergei-maertens** [comment] 2022-08-30 11:05
Reopening - there was some confusion with #1248

**Comment by sergei-maertens** [comment] 2022-09-01 07:07
It looks like you were right though - with the patch for #1248 I can not reproduce this. The validation error popped up for the date field which had a broken date-picker, after filling out this field I cannot reproduce this anymore.

So, fixed via #1248

**Closed by sergei-maertens** 2022-09-01 07:07 UTC
Labels: bug
