### ISSUE TITLE
import fails with error procestype-mismatch 

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#1065] opened 2021-11-19 09:37 UTC
**General information**
Open Zaak version:  (? latest-utrecht)

**Describe the bug**
when importing a casetype i get the following error: A validation error occurred while deserializing a ResultaatType {'non_field_errors': [ErrorDetail(string='selectielijstklasse should belong to the same procestype as zaaktype', code='procestype-mismatch')]} 
However the isnt any evident mismatch: when i check the resulaattypen, these all have a procestype that corresponds to the procestype of the casetype.  (the casetype has "Selectielijst procestype: 7 - Aangiften behandelen", and all 4 resultaattypen have "procestype: 7 - Aangiften behandelen" and "Selectielijstklasse: 7.1 - Verwerkt - vernietigen") 
![afbeelding](https://user-images.githubusercontent.com/40294293/142598337-83fbc088-072e-4d1a-926a-431f4e91f018.png)

**To Reproduce**
1. import zip into new catalog
( 2. select existing InformatieObjectType (in this case bijlage) )  
3. Choose Select. 

**Expected behavior**
The error mentioned above occurs.  

Casettype export: [melding-ondermijning-behandelen-2021-11-19.zip](https://github.com/open-zaak/open-zaak/files/7569197/melding-ondermijning-behandelen-2021-11-19.zip)

**Comment by sergei-maertens** [comment] 2021-11-24 07:35
This may be because of a mismatch in selectielijst year - can you verify that they're using the same year? 2017 vs. 2020?

**Comment by sergei-maertens** [comment] 2022-02-22 16:31
Possibly also related to #970

**Comment by sergei-maertens** [comment] 2022-10-14 08:50
The root cause of why the wrong year may have been saved should have been fixed via #970. Unfortunately, the only way to properly fix your data is by checking that the relations to selectielijst are indeed correct (with a  recent version of Open Zaak). Please let us know if the problem is not fixed via the above patches.

**Closed by sergei-maertens** 2022-10-14 08:50 UTC
Labels: bug
